name: deploy

on:
  push:
    branches: [ master ] # master 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Setup Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: npm install # 安装依赖

      - name: Build
        run: npm run build # 打包

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4 # 使用部署到 GitHub pages 的 action 使用别人写好的库
        with:
          publish_dir: ./dist # 部署打包后的 dist 目录
          github_token: ${{ secrets.VUE3_SUPER_ADMIN }} # secret 名
          TARGET_FOLDER: vue3-super-admin # 打包的文件将放到静态服务器 github-actions-demo 目录下
